### PR TITLE
Implement multiple transactions in block currently 5

### PR DESCRIPTION
**Pull request by QVDev**
Added block size 5 so every block can contain max 5 transactions. Also did some code formatting.

### CODE REVIEW

**Comment by QVDev** [comment]
Instead maybe later it can be improved by using the byte size of the transaction instead of the amount.
for reference
http://docs.oracle.com/javase/7/docs/api/java/lang/instrument/Instrumentation.html#getObjectSize(java.lang.Object)

**Review by rthotakura97 — CHANGES_REQUESTED** [review]
There are some conflicts with code you changed in the other pull request where you fixed the null pointer error. Do you think you could update the code for this pull request?

**Comment by rthotakura97** [comment]
I like the changes. Was able to merge it myself.

**Comment by QVDev** [comment]
Great to what do you think of actually using byte size?

**Comment by rthotakura97** [comment]
That works too.

---------------------------------------------------------
Rohit Thotakura
Computer Engineering
University of Illinois at Urbana Champaign
May 2019
----------------------------------------------------------

Sent from my Samsung Galaxy S8.

On Aug 29, 2017 1:02 PM, "QVDev" <notifications@github.com> wrote:

Great to what do you think of actually using byte size?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/rthotakura97/mini-blockchain/pull/1#issuecomment-325745755>,
or mute the thread

**Pull request merged**
